access_key         = "AKIAUVJ6CUNRSAUGINMC"
secret_key         = "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"
region             = "us-east-1"
instance_type      = "t2.micro"
ami                = "ami-053b0d53c279acc90"
security_group_name = "Groupe6"
key_pair_name      = "groupe6-keys"
private_key_path   = "C:\\Users\\d.gunes\\OneDrive - DAILYMOTION\\Bureau\\IPSSI\\COURS\\SEM7_Terraform\\mini_projet\\groupe6-keys.pem"
volume_size        = 10
